### ISSUE TITLE
hello，发送消息报错，能沟通下不

### ISSUE THREAD

**Issue by Elward-lv** [songxinjianqwe/Chat#7]
java.io.IOException: 你的主机中的软件中止了一个已建立的连接。
	at sun.nio.ch.SocketDispatcher.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:469)
	at cn.sinjinsong.chat.server.handler.message.MessageHandler.broadcast(MessageHandler.java:29)
	at cn.sinjinsong.chat.server.handler.message.impl.BroadcastMessageHandler.handle(BroadcastMessageHandler.java:33)
	at cn.sinjinsong.chat.server.ChatServer$ReadEventHandler.run(ChatServer.java:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Elward-lv** [comment]
我的，操作太快啦
